#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ezpark_db?currentSchema=reservation
#    username: ezpark_user
#    password: ezpark123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: reservation
#        format_sql: true
#    show-sql: true
#  kafka:
#    bootstrap-servers: localhost:9092
#
#server:
#  port: 8082
#
#logging:
#  level:
#    com.ezpark.io.reservation: DEBUG
#    org.hibernate.SQL: DEBUG