    version: '3.8'
    services:
      db:
        image: postgres:15
        container_name: ezpark-postgres
        environment:
          POSTGRES_DB: ezpark_db
          POSTGRES_USER: ezpark_user
          POSTGRES_PASSWORD: ezpark123
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
          - ./scripts/init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql
        networks:
          - db-network

      pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
          PGADMIN_DEFAULT_PASSWORD: "password"
        ports:
          - "80:80"
        depends_on:
          - db
        networks:
          - db-network

    networks:
      db-network:
        driver: bridge

    volumes:
      postgres_data: