spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ezpark_db}
    username: ${DB_USERNAME:ezpark_user}
    password: ${DB_PASSWORD:ezpark123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          default_schema: public
          create_namespaces: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: public
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.ezpark.io: ${LOG_LEVEL_APP:DEBUG}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE:DEBUG}
    org.springframework.kafka: ${LOG_LEVEL_KAFKA:DEBUG}
    org.springframework.transaction: DEBUG

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always