spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ezpark_db?currentSchema=customer
    username: ezpark_user
    password: ezpark123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: customer
        format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

logging:
  level:
    com.ezpark.io.customer: DEBUG
    org.hibernate.SQL: DEBUG